### ISSUE TITLE
Icons on wrong bars

### ISSUE THREAD

**Issue by Shadowigor** [monopsony/ElWigo#3] opened 2021-02-21 20:16 UTC
I noticed that sometimes the ability icons are shown on the wrong bar when you manually move boss abilities to a different bar. A few examples from CN:
 - Artificer: Only the first cast of Dimensional Tear is shown on the correct bar, subsequent ones are on the default bar
 - Shriekwing: Earsplitting Shriek is only moved to the correct bar during Blood Shroud, otherwise it's shown on the default bar
 - Sunking: Ember Blast is always shown on the default bar
And probably a few more that I forgot again.

**Comment by monopsony** [comment] 2021-02-24 10:37
Hey, thanks for pointing that out to me. It's something I've already noticed quite a few times (on Xymox especially because it is not 100% consistent), and I'm also aware of the root cause. There are many different fixes for this but I have not yet made up my mind as to what's best. Either way, I should be able to have it fixed in the next release.

**Closed as completed** 2024-08-16 17:44 UTC
